name: CI_Pipeline

on:
  push:
   branches : [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout_Code
        uses: actions/checkout@v5
      - name: Set_up_node.js
        uses: actions/setup-node@v3
        with: 
          node-version: 22
      - name: Install_dependencies
        run: npm install
      - name: Run_tests
        run: npm run test


# []: new line with 2 space and - for items
# {}: new line with 2 space
# "" : on same line